[server]
hostname = "test-vm"
listen = "0.0.0.0"
port = 2222
host_key_file = "host_key.pem"
rsa_host_key_file = "host_key_rsa.pem"
ip_log_file = "honeypot.log"
inactivity_timeout_secs = 360
auth_rejection_time_secs = 0
auth_rejection_time_initial_secs = 0

[credentials]
root = "toor"
admin = "admin"
ubuntu = "ubuntu"
